(progn
  (setq orbit1 (saw))
  (put orbit1 'freq (/ (* 60 11)))
  (setq rotation1 (saw))
  (put rotation1 'freq (/ (* 60 5)))
  (def planet (distance rotation size)
    (translate distance 0 0)
    (rotate-y rotation)
    (scale size size size)
    (tetrahedron))
  (def draw ()
    (background 0 0 0)
    (rotate-y (sigval orbit1))
    (color 180 (/ 7 10) 1)
    (planet 4 (sigval rotation1) (/ 3 4))
    (color 90 (/ 7 10) 1)
    (planet 2 (/ 2) (/ 2))))
