(progn
  (setq tri1 (tri))
  (put-slot tri1 'freq (/ 120))
  (setq saw1 (saw))
  (put-slot saw1 'freq (/ 120))
  (def draw ()
    (background 0 0 0)
    (translate (lerp -4 4 (sigval saw1))
               (lerp -4 4 (sigval tri1))
               0)
    (scale (/ 4))
    (cube)))
